# Docker compose file for running the LabCAS containers:
# labcas-backend
# labcas-ui
# nginx proxy

# Required env variables: 
# LABCAS_CONSORTIUM: name of consortium specific configuration
# LABCAS_PORT: host port that is proxied to Nginx port 80
# LABCAS_CONFIG: location of configuration directory
# LABCAS_STAGING: location of temporary data storage
# LABCAS_ARCHIVE: location of permanent sara storage
# LABCAS_HOME: location containig solr-index directory

# Required configuration files:
# $LABCAS_CONFIG/$LABCAS_CONSORTIUM/labcas.properties
# $LABCAS_CONFIG/$LABCAS_CONSORTIUM/labcas_certs
# $LABCAS_CONFIG/$LABCAS_CONSORTIUM/paste.cfg
# $LABCAS_CONFIG/$LABCAS_CONSORTIUM/ui.env

version: '3.3'

services:

   nginx:
     image: nginx
     #command: [nginx-debug, '-g', 'daemon off;']
     ports:
        - "${LABCAS_PORT}:80"
     volumes:
        # override default nginx configuration
        - ./nginx/conf/nginx_proxy.conf:/etc/nginx/conf.d/default.conf:ro
     depends_on:
       - labcas-backend 
       - labcas-ui

   labcas-backend: 
      image: edrn/labcas-backend:${LABCAS_BK_VERSION-latest}
      build:
        context: ./labcas-backend
      volumes: 
        - $LABCAS_STAGING:/usr/local/labcas/staging
        - $LABCAS_ARCHIVE:/usr/local/labcas/archive
        - $LABCAS_HOME/solr-index:/usr/local/labcas/home/solr-index
        - $LABCAS_HOME/products:/usr/local/labcas/home/products
        - $LABCAS_CONFIG/labcas.properties:/root/labcas.properties
        - $LABCAS_CONFIG/labcas_certs:/root/certs
      ports:
        - "8983:8983"
        
   labcas-client: 
      image: edrn/labcas-client:${LABCAS_BK_VERSION-latest}
      build:
        context: ./labcas-client
      volumes: 
        # NOTE: the labcas-client must share she same target filesystem as the labcas-backend
        # to be able to crawl a directory tree and submit publishing requests
        - $LABCAS_STAGING:/usr/local/labcas/staging
        - $LABCAS_ARCHIVE:/usr/local/labcas/archive
        # FIXME: for development only
        #- $HOME/eclipse-workspace/labcas-backend/common/src/main/python:/usr/local/labcas/python
      command: ["tail", "-f", "/dev/null"]
 
        
   labcas-ui: 
      image: edrn/labcas-ui:${LABCAS_UI_VERSION-latest}
      env_file: $LABCAS_CONFIG/ui.env
      volumes: 
        - $LABCAS_STAGING:/usr/local/labcas_staging
        - $LABCAS_CONFIG/labcas_certs:/app/certs
        - $LABCAS_CONFIG/paste.cfg:/app/persistence/paste.cfg
        - persistence:/app/persistence
      depends_on:
        - labcas-backend  
      healthcheck:
            test: ["CMD", "curl", "--fail", "http://labcas-ui:6543"]
            interval: 5m
            timeout: 10s
            retries: 3

volumes:
    persistence: