# Docker compose file for running the LabCAS containers:
# labcas-backend
# labcas-ui
# nginx proxy

# Required env variables: 
# LABCAS_NETWORK: pre-existing Docker network that connects all these containers
#                 when running on AWS with JPL security, it must be configured to
#                 connect to the internet
# LABCAS_PORT: host port that is proxied to Nginx port 80
# SOLR_PORT: port where Solr is available for local publishing operations
# WMGR_PORT: port where the OODT Workflow Manager is available for local publishing operations
# LABCAS_CONSORTIUM: name of consortium specific configuration
# LABCAS_INSTALL: location of LabCAS installation

# Required configuration files:
# $LABCAS_CONFIG/$LABCAS_CONSORTIUM/labcas.properties
# $LABCAS_CONFIG/$LABCAS_CONSORTIUM/labcas_certs
# $LABCAS_CONFIG/$LABCAS_CONSORTIUM/ui.env

version: '3.3'

networks: 
  default:
    external: 
      name: ${LABCAS_NETWORK}

services:

   nginx:
     image: nginx
     #command: [nginx-debug, '-g', 'daemon off;']
     ports:
        - "${LABCAS_PORT}:80"
     volumes:
        # override default nginx configuration
        - ./nginx/conf/nginx_proxy.conf:/etc/nginx/conf.d/default.conf:ro
        # static web content
        - $LABCAS_INSTALL/static:/usr/local/labcas/static
     depends_on:
       - labcas-backend 
       - labcas-ui

   labcas-backend: 
      image: edrn/labcas-backend:${LABCAS_BK_VERSION-latest}
      build:
        context: ./labcas-backend
      volumes: 
        - $LABCAS_INSTALL/staging:/usr/local/labcas/staging
        - $LABCAS_INSTALL/archive:/usr/local/labcas/archive
        - $LABCAS_INSTALL/home/solr-index:/usr/local/labcas/home/solr-index
        - $LABCAS_INSTALL/home/products:/usr/local/labcas/home/products
        - $LABCAS_INSTALL/static:/usr/local/labcas/static
        - $LABCAS_INSTALL/config/labcas.properties:/root/labcas.properties
        - $LABCAS_CERTS:/root/certs
      ports:  
        - "${SOLR_PORT}:8983"
        - "${WMGR_PORT}:9001"

        
   labcas-client: 
      image: edrn/labcas-client:${LABCAS_BK_VERSION-latest}
      build:
        context: ./labcas-client
      volumes: 
        # NOTE: the labcas-client must share she same target filesystem as the labcas-backend
        # to be able to crawl a directory tree and submit publishing requests
        - $LABCAS_INSTALL/staging:/usr/local/labcas/staging
        - $LABCAS_INSTALL/archive:/usr/local/labcas/archive
        # FIXME: for development only
        #- $HOME/eclipse-workspace/labcas-backend/common/src/main/python:/usr/local/labcas/python
      # keep the container running to execute publishing operations
      command: ["tail", "-f", "/dev/null"]
        
   labcas-ui: 
      image: edrn/labcas-ui:${LABCAS_UI_VERSION-latest}
      build: ./labcas-ui
      env_file: $LABCAS_INSTALL/config/ui.env
      volumes: 
        - $LABCAS_INSTALL/staging:/usr/local/labcas/backend/staging
        - $LABCAS_CERTS:/app/certs
        - persistence:/app/persistence
      depends_on:
        - labcas-backend  
      healthcheck:
            test: ["CMD", "curl", "--fail", "http://labcas-ui:6543"]
            interval: 5m
            timeout: 10s
            retries: 3
            
   labcas-publish-api:
     image: edrn/labcas-ui:${LABCAS_PUBLISH_API_VERSION-latest}
     build:
       context: ./labcas-publish-api
     ports:
       - "${PUBLISH_API_PORT}:5000"

volumes: 
  persistence: 