# Docker compose file for running the LabCAS back-end container

# Required env variables:
# LABCAS_STAGING: location of temporary data storage
# LABCAS_ARCHIVE: location of permanent sara storage

# Required files:
# ~/labcas.properties
# ~/labcas_certs

version: '3.3'

networks: 
  default:
    external: 
      name: labcas-network 

services:

   nginx:
     image: nginx
     container_name: nginx
     #command: [nginx-debug, '-g', 'daemon off;']
     ports:
        - "80:80"
     volumes:
        # override default nginx configuration
        - ./nginx/conf/nginx_proxy.conf:/etc/nginx/conf.d/default.conf:ro

   labcas-backend: 
      image: edrn/labcas-backend
      container_name: labcas-backend
      build:
        context: ./labcas-backend
      ports:
        - "8983:8983"
        - "9000:9000"
        - "9001:9001"
        - "8080:8080"
      volumes: 
        - $LABCAS_STAGING:/usr/local/labcas_staging
        - $LABCAS_ARCHIVE:/usr/local/labcas_archive
        - $LABCAS_HOME/solr-index:/usr/local/labcas/solr-index
        - $HOME/labcas.properties:/root/labcas.properties
        - $HOME/labcas_certs:/root/certs
        
   labcas-frontend: 
      image: edrn/labcas-ui:${LABCAS_UI_VERSION-latest}
      container_name: labcas-ui
      build:
        context: ./labcas-ui
      ports:
        - "6543:6543"
      env_file: .env
      volumes: 
        - $LABCAS_STAGING:/usr/local/labcas_staging
        - $LABCAS_ARCHIVE:/usr/local/labcas_archive
        - $HOME/labcas_certs:/app/certs
        - persistence:/app/persistence
        # FIXME
        #- $PWD/paste.cfg:/app/persistence/paste.cfg
      healthcheck:
            test: ["CMD", "curl", "--fail", "http://localhost:6543"]
            interval: 5m
            timeout: 10s
            retries: 3

volumes:
    persistence: