apiVersion: v1
kind: Service
metadata:
  name: labcas-backend
  labels:
    stack: labcas
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 8983 # host port
    targetPort: 8983 # container port
    protocol: TCP
    name: solr-port
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: fmgr-port
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: wmgr-port
  - port: 9002
    targetPort: 9002
    protocol: TCP
    name: rmgr-port
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: tomcat-port
  # the selector identifies the set of pods to load-balance against
  selector:
    stack: labcas
    tier: backend
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: labcas-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        stack: labcas
        tier: backend
    spec:
      containers:
      - name: labcas-backend
        image: edrn/labcas-backend:latest
        ports:
        - containerPort: 9000
        - containerPort: 9001
        #- containerPort: 9002
        - containerPort: 8983
        - containerPort: 8080
        volumeMounts:
        - name: labcas-archive
          mountPath: /usr/local/oodt/archive/
        - name: solr-index
          mountPath: /usr/local/oodt/solr-index/
      volumes:
      - name: labcas-archive
        emptyDir: {}
      - name: solr-index
        emptyDir: {}
