# Docker compose file for running the LabCAS back-end container

# Required env variables:
# LABCAS_STAGING: location of temporary data storage
# LABCAS_ARCHIVE: location of permanent sara storage

# Required files:
# ~/labcas.properties
# ~/labcas_certs

version: '3.3'

networks: 
  default:
    external: 
      name: labcas-network 

services:

   nginx:
     image: nginx
     container_name: nginx
     #command: [nginx-debug, '-g', 'daemon off;']
     ports:
        - "80:80"
     volumes:
        # override default nginx configuration
        - ./conf/nginx_proxy.conf:/etc/nginx/conf.d/default.conf:ro

   labcas-backend: 
      image: edrn/labcas-backend
      container_name: labcas-backend
      ports:
        - "8983:8983"
        - "9000:9000"
        - "9001:9001"
        - "8080:8080"
      volumes: 
        - $LABCAS_STAGING:/usr/local/labcas_staging
        - $LABCAS_ARCHIVE:/usr/local/labcas_archive
        - $LABCAS_HOME/solr-index:/usr/local/labcas/solr-index
        - $LABCAS_HOME/solr-home:/usr/local/labcas/solr-home
        - $HOME/labcas.properties:/root/labcas.properties
        - $HOME/labcas_certs:/root/certs
   
