# Docker compose file for running the LabCAS back-end container

# Required env variables:
# LABCAS_STAGING: location of temporary data storage
# LABCAS_ARCHIVE: location of permanent sara storage

# Required files:
# ~/labcas.properties

version: '3.4'

services:

   labcas-backend:
      image: edrn/labcas-backend
      container_name: labcas-backend
      ports:
        - "8983:8983"
        - "9000:9000"
        - "9001:9001"
        - "8080:8080"
      volumes: 
        - $LABCAS_STAGING:/usr/local/labcas_staging
        - $LABCAS_ARCHIVE:/usr/local/labcas_archive
        - $HOME/labcas.properties:/root/labcas.properties
        - $HOME/labcas_certs:/root/certs
   
